spring:
  devtools:
    restart:
      aditional-paths: src/main/java
  application:
    name: proveedor-service
  cloud:
    config:
      enabled: true
      uri: http://localhost:8004
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/proveedores
    username: postgres
    password: admin
  jpa:
  show-sql: true
  hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: create-drop