insert into proveedor_entity (proveedor_id, nombre, categoria, retencion) values ('35682', 'O''Keefe Group', 'C', 'No');
insert into proveedor_entity (proveedor_id, nombre, categoria, retencion) values ('95620', 'O''Keefe, Hodkiewicz and Reynolds', 'B', 'Si');
insert into proveedor_entity (proveedor_id, nombre, categoria, retencion) values ('36633', 'Price-Effertz', 'C', 'Si');
insert into proveedor_entity (proveedor_id, nombre, categoria, retencion) values ('32204', 'Brakus, Yundt and Herman', 'C', 'Si');
insert into proveedor_entity (proveedor_id, nombre, categoria, retencion) values ('18816', 'Macejkovic Group', 'C', 'Si');
insert into proveedor_entity (proveedor_id, nombre, categoria, retencion) values ('22744', 'O''Kon and Sons', 'A', 'Si');
insert into proveedor_entity (proveedor_id, nombre, categoria, retencion) values ('16880', 'Lemke Group', 'C', 'No');
insert into proveedor_entity (proveedor_id, nombre, categoria, retencion) values ('28039', 'Durgan-Murazik', 'A', 'Si');
insert into proveedor_entity (proveedor_id, nombre, categoria, retencion) values ('55481', 'Wiegand-Kihn', 'D', 'No');
insert into proveedor_entity (proveedor_id, nombre, categoria, retencion) values ('13795', 'Littel, Moore and Hammes', 'D', 'Si');